name: home
description: Home feature
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../../infrastructure/common/
  core:
    path: ../../infrastructure/core/

  # Network
  graphql_flutter: ^5.1.2
  # Caching
  hive: ^2.0.4

  # UI
  pagination_view:
    git:
      url: https://github.com/vedartm/pagination_view.git
  ant_icons: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  flutter_drawer_menu: ^0.1.2
  pinch_to_zoom_scrollable: ^0.1.1
  stream_transform: ^2.1.0

dev_dependencies:
  freezed: ^2.4.6
  build_runner: ^2.4.7
  injectable_generator:
    path: ../../infrastructure/injectable_generator
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true