# Melos settings and scripts
name: multi_package_workspace

versioning:
  mode: independent

packages:
  - apps/*
  - infrastructure/**
  - features/**

command:
  bootstrap:
    hooks:
      pre: dart run scripts/deps_fixer.dart
      post:
        melos exec -c 1 --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs;

scripts:
  fix:
    run: dart run deps_fixer.dart
    description: Fix dependencies according common_deps.yaml
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks
  format:
    run: melos exec -c 6 --fail-fast -- flutter format .
  analyze:
    run: melos exec -c 3 flutter analyze
    description: Run analyze for Flutter packages in this project
  test:
    run: melos run test:selective --no-select
    description: Run all Flutter tests in this project.
  test:selective:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub --reporter compact --no-test-assets"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - "*example*"
  install:
    run: melos exec -c 6 flutter pub get
    description: Install all dependencies
  clean:
    run: melos exec -c 6 -- flutter clean && melos run install
    description: Clean Flutter packages in this project and run bootstrap
  format:check:
    run: melos exec -c 6 --fail-fast -- flutter format --set-exit-if-changed --dry-run .
  codegen:
    run: melos exec -c 1 --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run code generation using build_runner
  codegen:selective:
    run: melos exec -c 1 --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Run code generation using build_runner in a specific package
    select-package:
      depends-on: "build_runner"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"
