name: melos_workspace
description: Melos workspace Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: any
  yaml_edit: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  melos: ^3.4.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
