name: core
description: A core package
version: 0.0.1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common/

  equatable: ^2.0.3
  get_it: ^9.2.1
  flat: ^0.5.0

  freezed_annotation: ^3.1.0
  # Network
  internet_connection_checker: ^3.0.1

  # Misc
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.28.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.4.7
  freezed: ^3.2.5
  injectable_generator:
    path: ../../infrastructure/injectable_generator/
  json_serializable: ^6.7.1
